require "fileutils"

module CarrierWave
  module Ffmpeg
    module Audio
      class Processor
        # Scope these under Processor so you can catch the ones generated by just this class.
        class RuntimeError < ::RuntimeError;end;
        class ArgumentError < ::ArgumentError;end;

        BIT_RATE = "128k".freeze
        SAMPLE_RATE = "44100".freeze

        class << self
          def convert(source, options)
            final_filename = tmp_filename(source: source, format: "mp3")
            system "ffmpeg -i #{source} -c:a libmp3lame -ab #{BIT_RATE} -ar #{SAMPLE_RATE} #{final_filename}"
            final_filename
          end

          def watermark(source, options)
            final_filename = tmp_filename(source: source, format: "mp3", prefix: "wtmk")
            watermark_file = options[:watermark]
            system "ffmpeg -i #{source} -i #{watermark_file} -filter_complex amerge -c:a libmp3lame -ab #{BIT_RATE} -ar #{SAMPLE_RATE} #{final_filename}"
            final_filename
          end

          private

          # Generate a temporary filename
          def tmp_filename source:, format:, prefix: nil
            ext = File.extname(source)
            source_filename_without_ext = File.basename(source, ext)
            File.join File.dirname(source), "tmp#{prefix.present? ? '_' + prefix : ''}_#{source_filename_without_ext}_#{Time.now.to_i}.#{format}"
          end
        end
      end
    end
  end
end
